server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: false


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

application:
  name: blog-search
  version: 1.0.0
  external-api:
    kakao:
      scheme: https
      host: dapi.kakao.com
      path: /v2/search/blog
      authorization: KakaoAK 7a06dbbb7157ea25c1b3a61102c9ce3f
    naver:
      scheme: https
      host: openapi.naver.com
      path: /v1/search/blog.json
      client-id: vKZOlRasLvIzKr2fJPqO
      client-secret: 6Oq3UjlVGH
